### ISSUE TITLE
Line length parameter for IRC dump

### ISSUE THREAD

**Issue by Underdoge** [BourgeoisBear/ansiart2utf8#1] opened 2017-07-25 07:08 UTC
Hello,

It would be nice to have a line length parameter to limit the output to a certain length for being able to dump the output to IRC without issues.

Or maybe a fork for ansiart2irc ?

Thanks!

**Comment by BourgeoisBear** [comment] 2017-07-25 07:16
I'm not an IRC user, so I'm not entirely sure what the problem is here.  It already has a -w parameter for setting the wrap length.  It defaults to 80 since that's what most ANSI art wrapped at.

One deficiency that I know the program has is dealing with relative motion escape codes.  I think it already handles forward-jumping ones, but makes no attempt at backward-jumps.  Most ANSI paint programs don't use backward-jumps in their output anyway, but if you run into a hand-coded ANSI file (especially ones that do animations, like on textfiles.com), they do have backward-jumps, and the ansiart2utf8 output will be incorrect.

**Comment by BourgeoisBear** [comment] 2017-07-25 07:18
By line length, do you mean a horizontal truncation?

**Comment by Underdoge** [comment] 2017-07-25 17:24
Thanks for the quick reply @BourgeoisBear! Yes I meant horizontal truncation.

I think the problem I'm seeing is due to a limitation in I[RC's standard](http://www.efnet.org/?module=docs&doc=7) which only allows 510 raw characters per line, which are easily exceeded with the regular UTF output.

For example one of my favorite ANSI [Blocktronics-WTF4_Megajoint.ans](http://sixteencolors.net/pack/blocktronics_wtf4/Blocktronics-WTF4_Megajoint.ans) renders beautifully [in the console](http://imgur.com/a/wsmrm) with the script as it currently is, but when trying to output it directly in IRC the lines get truncated by IRC's line limit [as seen here](http://imgur.com/a/sq0G1).

As I said this is definitely a limitation in IRC's standard, but it would be nice to see it working there too. The[ IRC standard in terms of formatting](https://github.com/myano/jenni/wiki/IRC-String-Formatting) is entirely a different animal. For the most part in IRC you need to save characters by only stating colors when the color changes, like some sort of compression.

Maybe I'll take a stab at it when I have some free time.

By the way thanks for this script, it is awesome!

**Comment by BourgeoisBear** [comment] 2017-07-25 18:23
@Underdoge,

Now that I have a user, that will probably light a fire under me to handle all of the ESC codes properly.  I'll see what I can do about the IRC issue.  Thanks! 

JS

**Comment by BourgeoisBear** [comment] 2017-08-04 09:17
@Underdoge,

Do you have a preference for handling the truncation?  Even in the terminal, each color-change is triggered by an escape sequence which is at least two characters, so for a "fixed" width graphic the per-line byte-lengths are all over the place (number of color-changes / ratio of of plain ASCII chars to UTF-8 translated box-drawing chars / etc).

Two approaches I can think of:

- **Best Effort**: Render as many characters-per-line as possible up to 510 chars.  More of the image would be rendered, but may have a jagged right-edge.

- **Uniform Width**: Pre-calculate worst-case for a visible column that fits in 510 bytes.  Render only up to that column.  Uniform width, but less of the image may be rendered.

In both cases, ensure that the escape-code-state at the truncated newline matches that of the original newline.

**Comment by Underdoge** [comment] 2017-08-05 00:17
Best Effort I think would better in my opinion.

Also I've been working on something like this myself, forking another script I found [here](https://gist.github.com/revmischa/4023167).

My [version](https://gist.github.com/Underdoge/799f20c3f5748cefb1ad26abc3eca675) is not perfect but it might give you some ideas.

Honestly I've been having a hard time getting used to this script's architecture and language (Perl) so I'm thinking of redoing it in javascript.

**Comment by BourgeoisBear** [comment] 2017-08-05 07:06
C is my "go-to" language for things like this, but its UTF-8 handling leaves something to be desired.  I knew that Go had solid UTF-8 support, so I went with that.  Not entirely satisfied with the fat binary though!

I've heard that Rust also has strong UTF-8 support.  If it makes a smaller binary, I may swap it all over to Rust.

**Comment by BourgeoisBear** [comment] 2017-08-12 12:19
I've added a best-effort per-line byte-truncation with the `-bytes` parameter in release-0.3b.  Let me know if this fixes your problem.

Thx.

JS

**Closed** 2021-11-20 00:16 UTC
